#include "config.h"

float MAX_CORRESPONDENCE_DISTANCE = 25.0f;
float TRANSFORMATION_DIFFERENCE_THRESHOLD = 0.01f;
float MAX_FITNESS_MSE = 100.0f;

float OVERLAP_SQRT_DISTANCE_THRESHOLD = 10.0f;
int OVERLAP_POINTS_THRESHOLD = 10;

float DENSE_CLUSTERING_NEIGHBOR_RADIUS = 5.0f;
int DENSE_CLUSTERING_NEIGHBOR_NUMBER = 4;